#' summarize the dataset generated by group_arrays()
#'
#' Given a dataset created with group_arrays(), this function lists
#' the samples represented by each consensus repeat, sorted by the
#' number of constituent samples (descending).
#'
#'
#' @param data An object created with group_arrays().
#' @return A tibble of CRISPR consensus repeats and the number of samples
#' in which a repeat is identified.
#' @export

group_summary <- function(data) {

  data |>
    dplyr::select(repcon_grp, repcon, id) |>
    unique() |>
    dplyr::group_by(repcon_grp, repcon) |>
    dplyr::summarise(id = list(id)) |>
    dplyr::rename(sample_list = id) |>
    dplyr::mutate(sample_count = lengths(sample_list)) |>
    dplyr::arrange(desc(sample_count)) |>
    dplyr::ungroup()

}
